### ISSUE TITLE
SLURMCluster doesn't seem to adapt the number of workers

### ISSUE THREAD

**Issue by twoertwein** [dask/dask-jobqueue#463] opened 2020-09-09 17:38 UTC
**What happened**:
`SLURMCluster` started but created only one workers even though it is ~~managed by a `Client` with `adapt`~~ supposed to adapt between 1 and 10 jobs.

**What you expected to happen**:
I expected dask to ask SLURM to create one workers, potentially wait for how quickly it finishes, and then create more workers (the graph has four independent parts).

**Minimal Complete Verifiable Example**:

```py
import time

import numpy as np
from dask.distributed import Client
from dask_jobqueue import SLURMCluster


def get_shape():
    # simulate some workload for adapt
    for i in range(10 ** 5):
        x = np.random.rand(1000, 100)
    # make sure we have enough time to spawn workers
    time.sleep(10)
    return x.shape


if __name__ == "__main__":
    # create simple task graph
    n = 4
    graph = {f"shape_{i}": (get_shape,) for i in range(n)}
    targets = [f"shape_{i}" for i in range(n)]

    # use SLURM
    workers = 10  # we shouldn't need more then n=4 workers

    slurm_kwargs = {
        "queue": "cpu_low,cpu_high,gpu_low",
        "resource_spec": "",
        "diagnostics_port": None,
        "ip": "10.1.188.1",
        "cores": 1,
        "memory": "2G",
        "processes": 1,
    }

    with SLURMCluster(**slurm_kwargs) as cluster:
        cluster.adapt(minimum_jobs=1, maximum_jobs=workers)  #  used minimum=1, maximum=workers before
        with Client(cluster, direct_to_workers=True) as client:
            print(client.get(graph, targets))
```
**Anything else we need to know?**:
There are enough free resources on the SLURM cluster available and there are no job spawning limits enforced.

**Environment**:

- Dask version: 2.25.0 and dask_jobqueue 0.7.1
- Python version: 3.8.5
- Operating System: CentOs 3.10.0-693.5.2.el7.x86_64
- Install method (conda, pip, source): conda

**Comment by ocaisa** [comment] 2020-09-09 17:47
To give you a quick answer, the kwargs you're after were changed a while ago to `minimum_jobs` and ` maximum_jobs`, see https://github.com/dask/dask-jobqueue/pull/346/files

**Comment by twoertwein** [comment] 2020-09-09 17:53
thank you @ocaisa ! I changed that but it still does work as expected. I'll update the example in a second.

**Comment by guillaumeeb** [comment] 2020-09-11 14:59
Hi @twoertwein,

I you case, using `minimum` or `minimum_jobs` shouldn't make any difference as you have only one worker process per job looking at your configuration.

I must admit I have trouble understanding your example based on graph construction, maybe you could try to use delayed instead? Something like (this is probably not right):
```python
delayed_computation = [delayed(get_shape)() for i in range(n)]
...
results = client.compute(delayed_computation)
```

I also see that you use `direct_to_workers` kwarg, I didn't know this one, but doc says : _Whether or not to connect directly to the workers, or to ask the scheduler to serve as intermediary_.

I don't think this is a good idea to bypass the scheduler when you want the cluster to be adaptative. Adaptative mode must gather information from the scheduler to know if it needs to scale up. Maybe you could try to remove this?

**Comment by twoertwein** [comment] 2020-09-11 15:35
thank you @guillaumeeb ! 

> I you case, using minimum or minimum_jobs shouldn't make any difference as you have only one worker process per job looking at your configuration.

as far as I understand `SLURMCluster` `cores` (how many cores per workers are we requesting) and `processes` (how many processes should one workers have) should not limit the number of jobs that may be created. The `n_workers` argument should set the number of workers. I try to avoid specifying `n_workers`  since it should dynamically estimate how many it needs.

> I must admit I have trouble understanding your example based on graph construction, maybe you could try to use delayed instead? Something like (this is probably not right):

I will look into using a different API to construct the graph. I like the custom [graph API](https://docs.dask.org/en/latest/custom-graphs.html).

> I also see that you use direct_to_workers kwarg, I didn't know this one, but doc says : Whether or not to connect directly to the workers, or to ask the scheduler to serve as intermediary.
> 
> I don't think this is a good idea to bypass the scheduler when you want the cluster to be adaptative. Adaptative mode must gather information from the scheduler to know if it needs to scale up. Maybe you could try to remove this?

Good point! I forgot why I use `direct_to_workers` (I probably thought it affect the network communication: every cluster node can directly talk to each other). Setting it to  `None` or `False` doesn't still results in only one workers.

**Comment by guillaumeeb** [comment] 2020-09-11 16:05
It would be helpful to visualize how Dask is planning to execute your Graph. As I'm not familiar with the use of Graphs and client.get, it's difficult for me to tell you how to do. Maybe you could store the return of client.get into a variable and try to call `visualize()` on it.

Also, using the Dashboard could give insights : it would give you the execution graph and how the tasks are scheduled.

What you should observe if adaptive was working is first a single task executed, and once it's finished some other workers should start to help finish the other ones. Could you try to increase the number of task to see if it changes something? Adaptive has a number of configuration options, and it may be possible that it determines it's not worth it starting other workers. Still, I believe this is something else.

I'll see if I can work on you example next week, but I can't promise anything, I have very limited bandwidth.

**Comment by twoertwein** [comment] 2020-09-11 17:10
thank you for the debugging pointers! I will look into that this weekend.

I will test `adapt` also with `LocalCluster`, to make sure that SLURM isn't interfering in an unexpected way.

**Comment by twoertwein** [comment] 2020-10-01 19:40
`LocalCluster` scales the number of workers up but `SLURMCluster` doesn't seem to do that. Setting `minimum_jobs` (for `SLURMCluster`) to 2 will spawn a second job but the `maximum_jobs` seems to be ignored.

Here is the graph visualization:
https://drive.google.com/file/d/1ZuIqLrYLwG2uAkG7iLsMGbVXzr5opy5a/view?usp=sharing

And here is the updated code:

```py
import time

import dask
from dask.distributed import Client, LocalCluster
from dask_jobqueue import SLURMCluster
from distributed.worker_client import get_worker


def test_fun():
    # make sure we have enough time to spawn workers
    print("worker", get_worker().name)
    time.sleep(60)
    return get_worker().name


if __name__ == "__main__":
    # SLURMCluster or LocalCluster
    slurm = True

    # create simple task graph
    n = 4
    graph = {f"test_{i}": (test_fun,) for i in range(n)}
    targets = [f"test_{i}" for i in range(n)]
    dask.visualize(graph, filename="simple.svg")

    workers = 10  # we shouldn't need more then n=4 workers

    # SLURM
    kwargs = {
        "n_workers": 1,
        "queue": "cpu_low,cpu_high,gpu_low",
        "resource_spec": "",
        "diagnostics_port": None,
        "ip": "10.1.188.1",
        "cores": 1,
        "memory": "2G",
        "processes": 1,
    }
    adapt = {"minimum_jobs": 1, "maximum_jobs": workers}  # minimum_jobs=2 will spawn a second worker
    cluster = SLURMCluster

    # or LocalCluster
    if not slurm:
        kwargs = {
            "n_workers": 1,
            "diagnostics_port": None,
            "threads_per_worker": 1,
            "memory_limit": 0,
            "processes": True,
        }
        cluster = LocalCluster
        adapt = {"minimum": 1, "maximum": workers}

    with cluster(**kwargs) as cluster:
        cluster.adapt(**adapt)
        with Client(cluster) as client:
            client.register_worker_callbacks(
                lambda dask_worker: print("setup", dask_worker.name)
            )
            print(client.get(graph, targets))
```

**Comment by twoertwein** [comment] 2020-10-03 18:17
I was able to narrow down a little bit :)

The memory utilization seems to prevent the adaptive upscaling. In

https://github.com/dask/distributed/blob/a80b867cf40b05aa423a19aea1a077764ffba0f4/distributed/scheduler.py#L5380

`limit` is always really high (constant, in my case 2000000000 - `"memory": "2G"`) while `total` is very small (it is growing, starts with 0, then 24, 48, ...).

For the `LocalCluster`, `limit` is 0 (`"memory_limit": 0`) and `total` is growing at the same rate: it allows to upscale as soon as `total` is non-zero.

`cpu` is in both cases 1.

**Comment by twoertwein** [comment] 2020-10-03 20:05
@guillaumeeb I think the if-conditions referenced above (in dask/distributed) seems to be wrong? Shouldn't it be
```py
if total <= 0.6 * limit:
    memory = 2 * len(self.workers)
else:
    memory = 0
```
More importantly, the adaptive scheduler needs to distinguish between creating more workers within a job (in that case it is necessary to check whether there is enough space for those workers) and creating more jobs (in that case we might either have no memory limit or query SLURM&Co for the available resources).

**Comment by twoertwein** [comment] 2020-11-15 20:05
I created a PR for dask-distributed that fixes this issue (and also ensures that there are not more than necessary number of workers). The PR also contains a simpler testcase to reproduce the issue:
https://github.com/dask/distributed/pull/4155/files#diff-413d6f55a708fcd529d5cb0b45208a3a49636e637bbfcada6de0949d37e6de50R483

**Comment by guillaumeeb** [comment] 2020-11-18 19:17
Wow, that's great @twoertwein.

Sorry for the lack of follow-up here, but I'm really glad you found the bug!

**Comment by twoertwein** [comment] 2020-11-18 21:55
if you have time @guillaumeeb (or anyone else familiar with the affected code), it would be great to get comments on the PR. The PR has been idling around for quite a while (except me occasionally doing: `git pull --rebase upstream master && git push --force`)

**Comment by guillaumeeb** [comment] 2020-11-24 17:15
I can't promise you, but I'll try to take a look at it in the next weeks.

**Comment by guillaumeeb** [comment] 2021-01-23 16:03
Hey @twoertwein!

I finally took a look at your issue... Hope you're still around. I see you've closed you issue in distributed, that's OK, I think I've got a solution for you.

So I've been playing a little with your example, and here's what I saw in my dashboard when launching your graph example:
![Graphs](https://user-images.githubusercontent.com/17138587/105606660-029ba180-5d9b-11eb-9e58-b17a94b44699.PNG)

This toy example is generating 4 __independent__ computations. Which means that Dask will treat them independently, and will need to compute a task for each of them before deciding if he can scale. This leads to a sequential execution, as we can see in the following screenshot:
![seqsuence](https://user-images.githubusercontent.com/17138587/105606740-6faf3700-5d9b-11eb-8a57-baef6f7be36f.PNG)

This is true with both any `JobQueueCluster`, as with `LocalCluster`.

However, if you launch the same computation again, now Dask has some insight on each of the graph part, and it does trigger scale-up, no matter wether on `JobQueueCluster` or `LocalCluster`, again. See screen:
![paralle](https://user-images.githubusercontent.com/17138587/105606823-c452b200-5d9b-11eb-9318-c50f0867c43b.PNG)

But this is not what we want. We want Dask to scale up as soon as the first task is terminated.

Here, I can't tell why the graph operation you do leads to this execution scheme, you may want to dig in that if you want... But what I can tell is that with a Delayed equivalent of your graph, all is working as expected. The code looks like this:

```python
delayed_tests=[]
for i in range(n):
    delayed_tests.append(dask.delayed(test_fun)())
#dask.visualize(delayed_tests)
dask.compute(delayed_tests)
```

Which leads to the following graph:
![graph](https://user-images.githubusercontent.com/17138587/105606962-6d011180-5d9c-11eb-884f-d9fff34e2839.PNG)

Quite similar to yours. But when computing this, Dask interprets it as a single computation with 4 similar tasks:
![Capture](https://user-images.githubusercontent.com/17138587/105606993-9752cf00-5d9c-11eb-88ab-a86474301c8e.PNG)

Leading to what we want, once the first tasks ends and Dask know how many time it takes, it triggers scale-up of our adaptative cluster:
![scale-up](https://user-images.githubusercontent.com/17138587/105607022-c79a6d80-5d9c-11eb-9d5e-516ee95330d5.PNG)

So I hope all this will help you understand how Dask works, and I'm sorry that the graph API you like didn't work as expected.

**Comment by guillaumeeb** [comment] 2021-01-23 16:17
OK, so the solution using graph is:
```python
n = 4
graph = {("test_fun", i): (test_fun,) for i in range(n)}
targets = [("test_fun", i) for i in range(n)]
dask.visualize(graph)
```

This will identify each task with the same name _test_fun_, and run as you expected!

But I still encourage you to build your graphs with `delayed` 😄.

**Comment by guillaumeeb** [comment] 2021-01-23 16:19
I'm closing this issue, feel free to reopen?

**Closed by guillaumeeb** 2021-01-23 16:19 UTC

**Comment by twoertwein** [comment] 2021-01-23 16:49
thank you for your in-depth answer! I will look into moving to `delayed` :) In my real code, I cannot give all tasks the same name since follow-up tasks aggregate only some of the tasks (at least I don't think that is possible in the dict graph since it associated parent tasks by a string. Probably works with `delayed` since I can just pass it a future).

While the PR was fixing my symptoms, it would just always spawn more workers (the memory condition was correct). I think the root cause is that the elapsed time of the tasks is not always updated correctly.

**Comment by twoertwein** [comment] 2021-01-23 17:06
quick follow up questions: is `scatter` or `delayed` recommended to distributed data to workers? I have been using scatter but the [best practises](https://docs.dask.org/en/latest/delayed-best-practices.html) also mention `delayed` to push data to workers. I think scatter was recommended in some wanring when I simply put large data in the tuple of the dict graph.

**Comment by guillaumeeb** [comment] 2021-01-23 20:07
> at least I don't think that is possible in the dict graph since it associated parent tasks by a string

I think that if delayed manage to do it, you can probably do the same using the tuple (func_name, index) as parent task, but I'd advice against it anyway (see https://docs.dask.org/en/latest/graphs.html: _Working directly with dask graphs is rare, unless you intend to develop new modules with Dask. Even then, dask.delayed is often a better choice_.

> I think the root cause is that the elapsed time of the tasks is not always updated correctly

The root cause is that dask needs a reference of a task time to decide to scale up or not. In your case, every task was identified as a new one during the first execution.

> is scatter or delayed recommended to distributed data to workers?

If you're referring tohttps://docs.dask.org/en/latest/delayed-best-practices.html#avoid-repeatedly-putting-large-inputs-into-delayed-calls, I think that when using delayed, you just stick with delayed. This way the all computing graph is known by Dask and it can recompute anything. Using scatter is more suited to Future API, but it may miss the recompute possibility with delayed. Anyway, you should absolutely use one of them.

**Comment by twoertwein** [comment] 2021-01-23 21:13
thank you very much!
