### ISSUE TITLE
sbatch command return string

### ISSUE THREAD

**Issue by leej3** [dask/dask-jobqueue#209] opened 2018-12-15 22:08 UTC
As described in #208 I am having issues with newer versions of dask-jobqueue on SLURM. Thanks to @guillaumeeb for diagnosing the problem.

With the command:
```
cluster = SLURMCluster(processes=6, cores=24, memory="20GB")
cluster.start_workers(n_workers)
```

I receive the error:
```
ValueError: Could not parse job id from submission command output.
```

It looks like the returned string is different on our cluster (NIH) from other slurm clusters. The expected string is [here](https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/tests/test_jobqueue_core.py#L89) but I instead see the number alone:

```
sbatch /tmp/tmp712szxvl.sh
```
```
15786755
```
And confirming that is the job id:
```
sjobs |grep 15786755
```
```
rodgersleejg  15786755  dask-worker  norm     R   ---           1:42           3:00:00      1     8  8GB/node cn3385  
```

/usr/local/slurm/bin/sbatch is actually a perl script to intercept and enforce fair usage of the job queue (I think) so perhaps this is the reason the returned string is slightly different.

Software versions:
```
dask 1.0.0 py_0 conda-forge
dask-core 1.0.0 py_0 conda-forge
dask-jobqueue 0.4.1 py_0 conda-forge
```

I'll be away from internet for a day or two but can test/submit a pull request upon my return.

**Comment by willirath** [comment] 2018-12-16 11:11
Are you sure you run a recent version of dask jobqueue? Your error message should come from here: https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L511

**Comment by willirath** [comment] 2018-12-16 12:38
Another possibility. We only parse stdout that we get from here

https://github.com/dask/dask-jobqueue/blob/821d3d9a5a019bddfc5fee555a3b50961d117e25/dask_jobqueue/core.py#L390

Does your sbatch print to stderr?

**Comment by leej3** [comment] 2018-12-16 17:08
Nice catch. Yes `sbatch /tmp/tmp712szxvl.sh 2 >/dev/null` gives no output.  Would there be a reason to send that to stderr or  should I ask for that to be changed?

Regarding version I'm on the latest from conda-forge. It looks like the code is slightly different but not significantly. The error raised in core.py:
```
    485         match = re.search(self.job_id_regexp, out)
    486         if match is None:
    487             msg = ('Could not parse job id from submission command '
    488                    "output.\nJob id regexp is {!r}\nSubmission command "
    489                    'output is:\n{}'.format(self.job_id_regexp, out))
--> 490             raise ValueError(msg)
    491 
    492         job_id = match.groupdict().get('job_id')
    493         if job_id is None:
    494             msg = ("You need to use a 'job_id' named group in your regexp, e.g. "
    495                    "r'(?P<job_id>\d+)', in your regexp. Your regexp was: "
```

**Comment by leej3** [comment] 2018-12-16 17:10
Apologies. I just spotted I didn't report the full error:
```
ValueError: Could not parse job id from submission command output.
Job id regexp is '(?P<job_id>\\d+)'
Submission command output is:
```

**Comment by willirath** [comment] 2018-12-16 18:19
Short term, I'd propose a workaround that aliases your sbatch to sth merging stdout and stderr. 


Am 16. Dezember 2018 18:08:55 schrieb john lee <notifications@github.com>:

**Comment by willirath** [comment] 2018-12-16 20:45
This could work (in bash):

function sbatch { $(which sbatch) $* 2>&1 }
export -f sbatch

To be run before starting the python process from which you set up the SLURMCluster.


Am 16. Dezember 2018 19:19:06 schrieb Willi Rath <wrath@geomar.de>:

**Comment by willirath** [comment] 2018-12-16 20:46
This could work (in bash):

```
function sbatch { $(which sbatch) $* 2>&1 } export -f sbatch
```

To be run before starting the python process from which you set up the SLURMCluster.

**Comment by leej3** [comment] 2018-12-17 14:59
It turns out the sbatch wrapper returns the raw job_id to stdout, not what I said about stderr (I can't figure out how I got nothing when I redirected stderr to /dev/null. Probably a silly error on my part). 

What instead was happening was that the SLURMCluster's  submit_command is set to 'sbatch --parsable'  (this was done in commit 7dfa0078fc874b0e1024637d4ca62c612c4961bc). This actually prevented the function hack from working. When passed this flag the wrapper prints nothing. 

Setting submit_command to 'sbatch' solves the problem but the more permanent fix of changing the wrapper script on our cluster was done so everything works as expected. Thanks for the help in debugging the problem. 

Is the '--parsable' needed here? It seems superfluous given the regex will pick-up on the job_id anyway

**Comment by guillaumeeb** [comment] 2018-12-17 16:03
> Is the '--parsable' needed here? It seems superfluous given the regex will pick-up on the job_id anyway

That was just to make things easier before using the regex IIRC. But this seems to be a standard Slurm command, so I don't see a strong reason to drop it. I feel that the problem is more on your cluster specific solution...

**Comment by leej3** [comment] 2018-12-17 16:08
Agreed. I'm happy with the solution and for the issue to be closed.

**Comment by guillaumeeb** [comment] 2018-12-17 20:31
Glad that you problem is solved! Closing.

**Closed by guillaumeeb** 2018-12-17 20:31 UTC
