### ISSUE TITLE
CI for Schedulers

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-jobqueue#2] opened 2018-03-01 23:00 UTC
Linking to @jhamman's [comment]( https://github.com/pangeo-data/pangeo/issues/85#issuecomment-360842913 ), one of the challenges here is setting up CI for Dask. There has been some already towards using SGE (particularly at dask-drmaa) for testing. Configuring other schedulers (e.g. SLURM, PBS, LSF, etc.) is possible, but can be a bit tricky. Docker helps with this, but it requires a fair bit of configuration to get right.

One resource that might be useful are [these Docker images]( https://bitbucket.org/deardooley/agave-docker/src/dc81db2504cb6f3f7f52778493040bd4005433f4/test-containers/schedulers/?at=master ), which include SLURM and TORQUE (similar to PBS). That said, I'm not sure what license applies to these. Also they may not work out of the box (as was my experience with using their Grid Engine some time back). That said, they should at least provide useful insights on how to get working Docker images for these different cases. For simplicity, would propose building and hosting images for respective schedulers so that CI can just download them.

**Comment by luizirber** [comment] 2018-03-01 23:02
This repo has an example using SLURM: https://github.com/Snakemake-Profiles/slurm

**Comment by luizirber** [comment] 2018-03-01 23:14
I can take a look for SLURM (can you assign this issue to me?)

**Comment by mrocklin** [comment] 2018-03-01 23:16
To be honest I rarely use github assignment.  It looks like this is difficult to do without having you as part of the organization (which is currently somewhat challenging).  We might have to go with informal assignment for the time being.

Regardless, thank you for stepping up!

**Comment by jakirkham** [comment] 2018-03-01 23:23
Grid Engine should basically be just copying over what dask-drmaa already has. Maybe that is the best place to start and then we can extend from there. Is Travis CI enabled here?

**Comment by mrocklin** [comment] 2018-03-01 23:23
Nope.  Nothing yet.

**Comment by jakirkham** [comment] 2018-03-01 23:24
Would you be willing to do that? I could copy over the testing code. Just don't think I have permissions to add CI is all.

**Comment by mrocklin** [comment] 2018-03-01 23:29
Do you know how I can give you that permission?

**Comment by jakirkham** [comment] 2018-03-01 23:31
Think I need to have admin on the repo as it requires the ability to add webhooks. Not sure if there is anything more granular. Honestly don't know if I'd need admin for anything else. Leave it up to you whether to grant it or not.

**Comment by mrocklin** [comment] 2018-03-01 23:33
OK, you have admin rights.  I guess the difference here is the owner/member of the org distinction?  Further reason to push on https://github.com/dask/dask/issues/3223

**Comment by mrocklin** [comment] 2018-03-01 23:34
@jhamman @jedwards4b you two also now have rights on this repository

**Comment by jakirkham** [comment] 2018-03-01 23:57
Thanks.

Agree that we need to figure out org rights. Will try to make next meeting so we can discuss more.

Enabled Travis CI, but told it to skip until there is a `.travis.yml` file.

**Comment by mrocklin** [comment] 2018-03-02 02:08
> Grid Engine should basically be just copying over what dask-drmaa already has. Maybe that is the best place to start and then we can extend from there. Is Travis CI enabled here?

You know, the funny thing is that if we got a testing system for GE then that might be enough motivation to implement an SGECluster here just to get the test coverage.  It's rare that one builds source to capture testing, but in this case the ratio of difficulty in writing testing code and source code is so great that it makes sense :)

Testament to @jedwards4b 's refactor of JobQueueCluster I guess :)

**Comment by jhamman** [comment] 2018-03-02 02:14
I have a fair bit of SGE experience, and a cluster that I could test this on apart from travis. I'd be happy to contribute the `SGECluster`. I'll open a separate issue.

**Comment by mrocklin** [comment] 2018-03-02 02:19
Note that SGE was the model system for https://github.com/dask/dask-drmaa ,
the other library that is most like this repo.

Historically I worked on dask-drmaa a year or so ago.  Folks like
@jakirkham picked it up and have evolved it since then.  When I then
prototyped the PBSCluster for Pangeo I based it somewhat off of the design
of dask-drmaa.  As a result the two libraries have an interesting shared
history.

**Comment by mrocklin** [comment] 2018-03-02 02:19
In particular, we have a docker-compose setup for SGE that works well on
travis-ci.  If I recall correctly this was designed by @quasiben

**Comment by guillaumeeb** [comment] 2018-03-04 14:32
Can non member of the org see what's happening on travis-ci for any dask repository?
Shall we fork the repository if we want to test/check the CI build?

**Comment by mrocklin** [comment] 2018-03-04 14:36
Yes, those links are public https://travis-ci.org/dask/dask

**Comment by guillaumeeb** [comment] 2018-03-04 15:20
How do you feel about using docker-hub provided images, such as https://hub.docker.com/r/pbspro/pbspro? Do we want to control the entire build cycle or not?
To go more into detail, this one depends on a build image with no Dockerfile provided (https://hub.docker.com/r/pbspro/pbsbase/), how do you feel about that too?

And lastly, I believe we want a minimaly representative test cluster, so with one master and two slaves such as what is done for dask/dask-drmaa, and not a one node master/slave cluster?

**Comment by jhamman** [comment] 2018-03-27 23:33
Ran across this dockerized slurm cluster today: https://github.com/giovtorres/slurm-docker-cluster

**Comment by guillaumeeb** [comment] 2018-04-16 08:11
I propose to close this issue by opening more specific ones, e.g. one for PBS and one for SLURM. We already have basic CI with unit tests and for SGE.
Are you OK with this?

**Comment by guillaumeeb** [comment] 2018-04-20 19:58
I think this issue can be closed with ##23, #27, #41 and #42.

**Closed** 2018-04-20 21:26 UTC
