### ISSUE TITLE
not working with python 2

### ISSUE THREAD

**Issue by leej3** [dask/dask-jobqueue#37] opened 2018-04-17 20:12 UTC
Having installed dask_jobqueue with:
`pip install git+https://github.com/dask/dask-jobqueue.git#egg=0.1.0`

I get the following error upon import:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rodgersleejg/anaconda3/envs/dask_py2/lib/python2.7/site-packages/dask_jobqueue/__init__.py", line 3, in <module>
    from .pbs import PBSCluster
  File "/Users/rodgersleejg/anaconda3/envs/dask_py2/lib/python2.7/site-packages/dask_jobqueue/pbs.py", line 11, in <module>
    class PBSCluster(JobQueueCluster):
  File "/Users/rodgersleejg/anaconda3/envs/dask_py2/lib/python2.7/site-packages/docrep/__init__.py", line 376, in replace
    func.__doc__, indent=indent, stacklevel=4)
AttributeError: attribute '__doc__' of 'type' objects is not writable
```

**Comment by guillaumeeb** [comment] 2018-04-17 20:15
Same issue as #35!

I am working on it right now on #29.

**Comment by leej3** [comment] 2018-04-17 20:19
apologies. forgot to check. Thanks

**Comment by guillaumeeb** [comment] 2018-04-17 20:27
No problem :)

**Comment by lesteve** [comment] 2018-04-18 06:12
Duplicate of #35.

**Closed by lesteve** 2018-04-18 06:12 UTC

**Comment by lesteve** [comment] 2018-04-18 06:13
> Having installed dask_jobqueue with:
pip install git+https://github.com/dask/dask-jobqueue.git#egg=0.1.0

Just FYI because 0.1 is a released version I believe you can just do `pip install dask-jobqueue`.
