### ISSUE TITLE
all jobs get submitted to the same worker on SLURMCluster

### ISSUE THREAD

**Issue by ptrab** [dask/dask-jobqueue#199] opened 2018-11-19 12:38 UTC
Hi,

I am trying to use dask-jobqueue for an embarrassing parallel calculation, but it does not work how I expect it. I guess, there is a tremendous misunderstanding at my site.

So, I setup my cluster like following:
```
from dask_jobqueue import SLURMCluster
slurm_cluster = SLURMCluster(processes=1,
                             cores=36,
                             memory="150GB",
                             job_extra=["--get-user-env",
                                        "--exclusive",
                                        "--account=theochem"],
                             env_extra=["module load qchem/5.1",
                                        "cd /path/to/some/directory/"],
                             walltime="01:00:00",
                             queue="s_standard"
                             )
slurm_cluster.adapt(minimum=1, maximum=32)
slurm_client = Client(slurm_cluster)
```

I then have a function, that is called:
`values = calculate_all_points(points, args, slurm_client)`

which maps my calculation on the clients:
```
def calculate_all_points(points, args, client):
          initialization ...
          points_combined = ...

      future = client.map(program, points_combined)
      values = client.gather(future)
```

… where each 'program' call needs all the complete node resources.

When I start my script, it invokes one worker, which is expected as of the adaptive worker command. Also, after certain amounts of time, new workers are generated and deleted.

The problem is, that no worker except the first gets used but all jobs are submitted to the first worker only.

Do you have any idea about where my error lies?

Thank you very much in advance!
Philipp

**Comment by mrocklin** [comment] 2018-11-19 13:35
They will all be assigned to a single worker to start because you only have
one worker.  Then the adaptive system will see that it needs more workers
and ask for them.  Once they arrive then tasks should start to spread
around.  This is only likely to happen after the first task finishes
though.  Dask will want to get an estimate for how long your tasks run
before it's comfortable doing the load balancing.

**Comment by guillaumeeb** [comment] 2018-11-19 15:19
> … where each 'program' call needs all the complete node resources.

Could you elaborate on this? What is the length of `points_combined`? What is the duration of a single `program` call?

> Also, after certain amounts of time, new workers are generated and deleted.

After what amount of time? Are workers deleted just after creation?

**Comment by ptrab** [comment] 2018-11-20 10:08
Thank you both for your answers. You are right, I might need to elaborate a little more, esp. as I don't use dask-jobqueue and dask in the sense it was programmed, I guess.
As far as I understood, dask is meant to do many small calculations for, e.g., a big array as efficient as possible by spreading the single calculations across many cpus. That is not what I am doing and I am trying to use it "only" as a real nice and easy to use submit script. :)

My program is an external program that has nothing to do with python. My python script writes the input, the map then calls the external program to calculate the written inputs and afterwards python again comes into play, when it comes to evaluate the output.
I thought, that I just would need to set the dask-workers to what my calculation would need (36 cores, 150gb ram, roughly the node specification) and set the number of processes per worker to one. In my head, this means that every worker can only handle one process with 36 cores and 150gb ram.

If you say, that all the jobs get submitted to the first worker, as it is the only one at the beginning, that is obviously against my understanding of my chosen parameters.

The length of `points_combined` is not fixed, but will most probably be less than 100. A single `program` call will take anything (as it depends on the molecular size, the calculation method, ...) from seconds for my test cases to minutes/hours for the real systems.

After what amount of time are new workers spawned? The first new come into play at about 5 to 10 minutes. Then they are created and deleted faster.
Are the workers deleted just after creation? It depends; some of them run for only a few seconds, but most then for some minutes.

**Comment by guillaumeeb** [comment] 2018-11-20 11:38
> My program is an external program that has nothing to do with python. My python script writes the input, the map then calls the external program to calculate the written inputs and afterwards python again comes into play, when it comes to evaluate the output.

That's a totally fine usage of Dask, more as a tasks/jobs scheduler. I also use it in my workflows.

> I thought, that I just would need to set the dask-workers to what my calculation would need (36 cores, 150gb ram, roughly the node specification) and set the number of processes per worker to one. In my head, this means that every worker can only handle one process with 36 cores and 150gb ram.

That is where the problem is I think, you're telling Dask that it can use the 36 cores to schedule tasks, so it will be able to launch 36 instances of your program in parallel. So 100 points will use at most 3 workers. I believe you should take a look to #181 which gives several solutions to your problem.

As for the adaptive strange behavior (starting and stopping worker), it is probably due to the long and variable duration of your program calls and the way adaptive mode is coded. There is also a discussion that may be related in #190.

**Comment by ptrab** [comment] 2018-11-20 13:07
> That is where the problem is I think, you're telling Dask that it can use the 36 cores to schedule tasks, so it will be able to launch 36 instances of your program in parallel. So 100 points will use at most 3 workers. I believe you should take a look to #181 which gives several solutions to your problem.

But shouldn't the `processes = n` regulate this? The documentation says regarding the [configuration](https://jobqueue.dask.org/en/latest/configuration.html):
>     cores=24,             # Number of cores per job
>     memory='100GB',       # Amount of memory per job
>     processes=6,          # Number of Python processes to cut up each job

So, in my job specification I say that I have per job: 1 process, 36 cores and 150GB memory.

---

However, as I am now aware of this, I simply say that each worker has 1 process and 1 core in combination with the `--exclusive` statement, which blocks the whole node for me and dask thinks, that per worker only one job can run. My external program uses the cores from another independent statement then.
This works quite well, as far as I can tell so far. Many workers are running, each has only one job running.

Thank you very much!

**Comment by guillaumeeb** [comment] 2018-11-20 16:07
I guess the documentation is not clear. By default, you launch only one process, but `cores` threads per dask worker. If you declare n processes, you will launch n worker process, and `cores` / n threads per dask worker.

This is the difference between multi processing and multiple threads, you're not forced to fork several processes to parallelize code. Dask can use multi-threading or multi-processing. You only need multi-processing if your process are GIL bounded, which does not seem to be the case.

See also dask-worker cli arguments, that are used by dask-jobqueue:
````
  --nthreads INTEGER            Number of threads per process.
  --nprocs INTEGER              Number of worker processes to launch.
````

Anyway, glad to here your problem is solved, the solution you propose is yet another one that your scheduler allows! However, be careful if you only book one cpu in your reservation to SLURM, your job might get killed if it uses more. But maybe the `--exclusive` option handle this well.

If this issue is fixed, is it OK to close it?

**Comment by ptrab** [comment] 2018-11-20 20:30
Indeed, I am sure that I read somewhere that for, e.g., hybrid OpenMP/OpenMPI the `--exclusive` flag is the way to go, as for the scheduler one needs to choose the number of the OpenMPI processes but in the end needs the (OpenMPI * OpenMP) cores.

Yes, it is working now as it should and can be closed.

**Comment by guillaumeeb** [comment] 2018-11-20 21:19
Perfect!

**Closed by guillaumeeb** 2018-11-20 21:19 UTC
Labels: usage question
