### ISSUE TITLE
Issues running jobs on Cheyenne using SLURM

### ISSUE THREAD

**Issue by gelsworth** [dask/dask-jobqueue#314] opened 2019-08-14 20:15 UTC
I am having issues running a job on Cheyenne using SLURM. I am able to connect to a node and can kill previous jobs that were launched using the `!scancel JOBID` command. However, although the jobs will disappear temporarily, when I restart and clear kernel output they will reappear. 

I am also unable to access the 8787 port for my currently running job. It appears to be in use by another user (the number of workers doesn't match the number I specified).

Any help canceling workers permanently in SLURM would be appreciated.
![Screen Shot 2019-08-14 at 2 11 45 PM](https://user-images.githubusercontent.com/46970446/63052793-84488980-be9d-11e9-9408-44be111f1364.png)

**Comment by guillaumeeb** [comment] 2019-08-14 20:37
> when I restart and clear kernel output they will reappear

This is strange. Workers should not appear unless you call `scale` function.
To stop all workers, just call `cluster.scale(0)`.

> I am also unable to access the 8787

This is not a problem, either it is someone else, or one of your previously started Scheduler, anyway, Dask will use another port. In your example, Dashboard can accessed at port 39672, or by clicking the link in your client representation in the notebook.

**Comment by gelsworth** [comment] 2019-08-14 20:51
The problem with access port 8787 is that I am ssh tunneling on Cheyenne and the ssh tunnels to port 8787 exclusively. So I can't reassign another port to access.

**Comment by mrocklin** [comment] 2019-08-14 21:48
You can probably specify another port with `dashboard_address=":8797"` or
something similar.  That way you can specify a particular port that others
are unlikely to use.  You might also want to install jupyter-server-proxy (
https://github.com/jupyterhub/jupyter-server-proxy), which the dask
scheduler will use if it is installed (see their docs for operation)

**Comment by jhamman** [comment] 2019-08-15 04:39
@gelsworth - do you know about https://jupyterhub.ucar.edu? This eliminates the need to do any ssh tunneling on Cheyenne or Casper.

**Comment by gelsworth** [comment] 2019-08-15 15:22
Yes, I just got access to jupyterhub through UCAR. The login without a YubiKey was a bit unintuitive so I contacted CISL support. I can now login using my username and my password,'DUO passcode'. I'm going to try this to avoid the ssh tunneling and see if I can run my script successfully. Thank you for all the helpful comments!

**Comment by guillaumeeb** [comment] 2019-10-11 20:08
Closing this as it looks the problem is solved. Feel free to re-open if you have more questions.

**Closed by guillaumeeb** 2019-10-11 20:08 UTC
