### ISSUE TITLE
CI is currently failing

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#613] opened 2023-08-04 09:34 UTC
Two things to look at:
- none build which mainly do code formatting checks (see https://github.com/dask/dask-jobqueue/pull/610#issuecomment-1665311514).
- Docker image builds, might be due to Python version problem. (https://github.com/dask/dask-jobqueue/pull/606#issuecomment-1579045899)

**Comment by jrueb** [comment] 2023-08-04 09:37
One thing I noticed is that this looks really outdated
https://github.com/dask/dask-jobqueue/blob/4bbd0a08342926ee8728ccd9a4559be3aa3ec628/.pre-commit-config.yaml#L7
flake8 moved to github years ago, see https://flake8.pycqa.org/en/latest/release-notes/4.0.0.html "Migrate from GitLab to GitHub"

**Comment by kaelancotter** [comment] 2024-03-13 00:54
Are you looking for help with this?

**Comment by guillaumeeb** [comment] 2024-03-13 10:57
Definitely!

**Comment by kaelancotter** [comment] 2024-03-15 23:06
Created PR [636](https://github.com/dask/dask-jobqueue/pull/636)  to resolve CI failures.  
Unfortunately CI fails in the PR since the updated images aren't pushed from the build step if its a PR - so CI action is still using the old docker images.
LMK if there's another direction I should take this to deal with the docker image catch-22

Specific to SGE tests - adding the --full-trace flag got rid of the seg fault, but I don't have a good root cause analysis.

This PR also doesn't address CI for documentation.

**Comment by jacobtomlinson** [comment] 2024-08-21 15:18
CI is in a much better place. #653 is still outstanding but I think we can close this issue in favour of that one.

**Closed by jacobtomlinson** 2024-08-21 15:18 UTC
