### ISSUE TITLE
PBS scheduling reports error on the generated PBSCluster job scripts

### ISSUE THREAD

**Issue by Djeutsch** [dask/dask-jobqueue#458] opened 2020-08-14 13:20 UTC
Hello,

I've been trying to invoke dask in data processing work by asking for more memory using `dask-jobqueue` (**v0.7.1**) on an HPC cluster that uses PBS scheduling. The following are the steps I used based on this [Dask jobqueue Documentation](https://jobqueue.dask.org/en/latest/howitworks.html).

```python
from dask_jobqueue import PBSCluster
from dask.distributed import Client

cluster = PBSCluster(cores=24,
                     memory="108GB",
                     queue="internal",
                     project="ERTH0834",
                     resource_spec="select=1:ncpus=24:mem=120GB",
                     walltime="05:00:00",
                     interface="ib0",
                     scheduler_options={"dashboard_address": ":9375"})

cluster.scale(jobs=8)
client = Client(cluster)
```

After running this script I was expected things to work just fine, but I am getting error message like the following:

```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/asyncio/tasks.py:596> exception=RuntimeError('Command exited with non-zero exit code.\nExit code: 32\nCommand:\nqsub /var/tmp/pbs.2985597.sched01/tmpzidjg2zw.sh\nstdout:\n\nstderr:\nqsub: Error: You must request a project with -P <project>.\n\n')>
Traceback (most recent call last):
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/distributed/deploy/spec.py", line 50, in _
    await self.start()
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 310, in start
    out = await self._submit_job(fn)
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 293, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 393, in _call
    "stderr:\n{}\n".format(proc.returncode, cmd_str, out, err)
RuntimeError: Command exited with non-zero exit code.
Exit code: 32
Command:
qsub /var/tmp/pbs.2985597.sched01/tmpzidjg2zw.sh
stdout:

stderr:
qsub: Error: You must request a project with -P <project>.
```
When I print the job script it generates the following scripts where I am getting **-A** for project key instead of **-P** as normally required by PBS scheduling.

```bash
#!/usr/bin/env bash

#PBS -N dask-worker
#PBS -q internal
#PBS -A ERTH0834
#PBS -l select=1:ncpus=24:mem=120GB
#PBS -l walltime=05:00:00

/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/bin/python -m distributed.cli.dask_worker tcp://172.19.2.39:37047 --nthreads 24 --memory-limit 108.00GB --name name --nanny --death-timeout 60 --interface ib0
```
I thought there may be a way to update **-A** with **-P**, but I am stuck. Please, any help would be greatly appreciated.

Many thanks in `advance,`
Djeutsch

**Comment by ocaisa** [comment] 2020-08-14 14:06
That's not normal for PBS according to http://docs.adaptivecomputing.com/torque/4-0-2/Content/topics/commands/qsub.htm (but I don't use PBS, so maybe this info is outdated?).

You can always use the `job-extra` kwarg to set unusual/alternative parameters, in this case
```
job-extra=['-P ERTH0834'],
```
should hopefully do the job.

**Comment by Djeutsch** [comment] 2020-08-14 22:49
@ocaisa,  That fixes the error issue but the job submission is not going through as it generates the following message
```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/asyncio/tasks.py:596> exception=RuntimeError('Command exited with non-zero exit code.\nExit code: 159\nCommand:\nqsub /var/tmp/pbs.2986504.sched01/tmps3km33i4.sh\nstdout:\n\nstderr:\nqsub: Unauthorized Request \n\n')>
Traceback (most recent call last):
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/distributed/deploy/spec.py", line 50, in _
    await self.start()
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 310, in start
    out = await self._submit_job(fn)
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 293, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 393, in _call
    "stderr:\n{}\n".format(proc.returncode, cmd_str, out, err)
RuntimeError: Command exited with non-zero exit code.
Exit code: 159
Command:
qsub /var/tmp/pbs.2986504.sched01/tmps3km33i4.sh
stdout:

stderr:
qsub: Unauthorized Request 
```

**Comment by Djeutsch** [comment] 2020-08-14 22:51
@ocaisa,  That fixes the error issue but the job submission is not going through as it generates the following message
```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/asyncio/tasks.py:596> exception=RuntimeError('Command exited with non-zero exit code.\nExit code: 159\nCommand:\nqsub /var/tmp/pbs.2986504.sched01/tmps3km33i4.sh\nstdout:\n\nstderr:\nqsub: Unauthorized Request \n\n')>
Traceback (most recent call last):
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/distributed/deploy/spec.py", line 50, in _
    await self.start()
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 310, in start
    out = await self._submit_job(fn)
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 293, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/home/ldjeutchouang/scratch/CONDA/envs/researchPy37/lib/python3.7/site-packages/dask_jobqueue/core.py", line 393, in _call
    "stderr:\n{}\n".format(proc.returncode, cmd_str, out, err)
RuntimeError: Command exited with non-zero exit code.
Exit code: 159
Command:
qsub /var/tmp/pbs.2986504.sched01/tmps3km33i4.sh
stdout:

stderr:
qsub: Unauthorized Request 
```

**Comment by ocaisa** [comment] 2020-08-15 05:50
I assume that submitting the jobscript by hand results in the same error, so I would compare it to examples you have for your site to understand where the issue is coming from (or ask the admins to take a look at the jobscript). Try manually tweaking the jobscript until you can get it to submit correctly. Once you know what the script should look like, you can figure out how to tweak your cluster configuration.

**Comment by guillaumeeb** [comment] 2021-01-23 23:17
Totally agree with @ocaisa. You probably have some qsub option that don't work with your cluster's restrictions. Maybe try to remove the `project="ERTH0834",` part? Or maybe this comes from the resources_spec.

**Comment by guillaumeeb** [comment] 2021-09-03 21:37
Closing as stalled. @Djeutsch feel free to reopen if  you've got something to add.

**Closed by guillaumeeb** 2021-09-03 21:37 UTC
Labels: PBS
